name: mini_service_booking
description: "Flutter technical interview."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  device_preview: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  logger: ^2.5.0
  connectivity_plus: ^6.1.3
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^9.0.2
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  image_cropper: ^9.0.0
  flutter_zoom_drawer: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mime: ^2.0.0
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.5
  flutter_floating_bottom_bar: ^1.2.1+1
  floating_bottom_navigation_bar: ^1.5.2
  photo_view: ^0.15.0
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.4.1
  redacted: ^1.0.13
  loading_animation_widget: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable:
  build_runner: ^2.4.15
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/gibe-market-logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/gibe-market-logo.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/gibe-market-logo.png
    icon_background_color: "#ffffff"


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
